version: "3.1"
services:
 

  db-initializer:
    image: gestionedipendenti/attendance-management-db-init-migrate:1.0.0
    container_name: db-initializer
    restart: always
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=192.168.1.242
      - DATABASE_PORT=5432
