version: "3.1"
services:
 
  attendance-management-backend:
    image: gestionedipendenti/attendance-management-be:1.0.0
    container_name: attendance-management-backend
    restart: always
    volumes:
      - backend-data:/opt/
    #    -----------------UNCOMMENT THIS LINE IF YOU WANT TO ENABLE SSL -- YOU HAVE TO PROVIDE ALSO A VALID CERTIFICATE named certificate.p12------------------
    #  - ./certificate.p12:/opt/certificate.p12
    environment:
      # replace the jwt value with a secret (just a random long string at least 54 chars)
      - SECURITY_JWT_SECRET=x8NbAp6tSEfsUHXUF46AElX6UyRTYhq33fOABk1oiAwGG24LoF4vHENCAcI70YdQwmLWV67TFQaSWjqo
      - PERSISTENCE_DATASOURCE_URL=jdbc:postgresql://pg-database:5432/postgres
      # replace with username and password used in postgres database
      - PERSISTENCE_DATASOURCE_PASSWORD=root
      - PERSISTENCE_DATASOURCE_USERNAME=postgres
      - FILE-MANAGER.STANDARD-FS.BASE-PATH=/opt/AppFiles/AttendanceManagement_Files
      - TEMP-FILE-DIRECTORY=/opt/AppFiles/AttendanceManagement_Files/TEMP
    #    -----------------UNCOMMENT THIS LINES IF YOU WANT TO ENABLE SSL---------------------
    #  - SERVER_SSL_KEY-STORE=/opt/certificate.p12
    #  - SERVER_SSL_KEY-STORE-PASSWORD=password
    #  - SERVER_SSL_KEY-STORE-TYPE=pkcs12
    #  - SERVER_SSL_KEY-ALIAS=localhost
    #  - SERVER_SSL_KEY-PASSWORD=password

    networks:
      - attendancemanagementnet
    ports:
      - "8080:8080"
    depends_on:
      pg-database:
        condition: service_healthy



  attendance-management-frontend:
    image: gestionedipendenti/attendance-management-fe:1.0.0
    container_name: attendance-management-frontend
    restart: always
    environment:
      # replace API_URL with the correct url
      - API_URL=http://localhost:8080
      - DEBUG=false
    ports:
      - "8081:80"
  
  

  pg-database:
    image: postgres:10.16-alpine
    container_name: pg-database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      #- POSTGRES_DB=rainbow_database
    networks:
      - attendancemanagementnet
    volumes:
      - database-data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    # use ports config if you want to expose database to external access
    #ports:
    #  - "5432:5432"


  database-initializator-migrator:
    image: gestionedipendenti/attendance-management-db-init-migrate:1.0.0
    container_name: database-initializator-migrator
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=pg-database
      - DATABASE_PORT=5432
    depends_on:
      pg-database:
        condition: service_healthy
    networks:
      - attendancemanagementnet

  


volumes:
  backend-data:
  database-data:


networks:
  attendancemanagementnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.248.9.0/24 # Avoid address collision with local network